//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gpa
    {
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public string Batch { get; set; }
        public string Semester { get; set; }
        public Nullable<int> CreditHours { get; set; }
        public Nullable<int> TotalMarks { get; set; }
        public Nullable<int> ObtainedMarks { get; set; }
        public Nullable<double> Gpa1 { get; set; }
        public Nullable<double> GradePoint { get; set; }
    
        public virtual StudentRegistry StudentRegistry { get; set; }
        public virtual TotalCourseMark TotalCourseMark { get; set; }
    }
}
