//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tloginEntities1 : DbContext
    {
        public tloginEntities1()
            : base("name=tloginEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<Cdetail> Cdetails { get; set; }
        public virtual DbSet<flogin> flogins { get; set; }
        public virtual DbSet<Gpa> Gpas { get; set; }
        public virtual DbSet<StudentRegistry> StudentRegistries { get; set; }
        public virtual DbSet<TotalCourseMark> TotalCourseMarks { get; set; }
        public virtual DbSet<makeupSchedule> makeupSchedules { get; set; }
    }
}
