//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalCourseMark
    {
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public string Batch { get; set; }
        public string Semester { get; set; }
        public Nullable<int> CourseId1 { get; set; }
        public string CourseTitle1 { get; set; }
        public Nullable<int> CreditHours1 { get; set; }
        public Nullable<int> ObtainedMarks1 { get; set; }
        public Nullable<int> TotalMarks1 { get; set; }
        public Nullable<int> CourseId2 { get; set; }
        public string CourseTitle2 { get; set; }
        public Nullable<int> CreditHours2 { get; set; }
        public Nullable<int> ObtainedMarks2 { get; set; }
        public Nullable<int> TotalMarks2 { get; set; }
        public Nullable<int> CourseId3 { get; set; }
        public string CourseTitle3 { get; set; }
        public Nullable<int> CreditHours3 { get; set; }
        public Nullable<int> ObtainedMarks3 { get; set; }
        public Nullable<int> TotalMarks3 { get; set; }
        public Nullable<int> CourseId4 { get; set; }
        public string CourseTitle4 { get; set; }
        public Nullable<int> CreditHours4 { get; set; }
        public Nullable<int> ObtainedMarks4 { get; set; }
        public Nullable<int> TotalMarks4 { get; set; }
        public Nullable<int> CourseId5 { get; set; }
        public string CourseTitle5 { get; set; }
        public Nullable<int> CreditHours5 { get; set; }
        public Nullable<int> ObtainedMarks5 { get; set; }
        public Nullable<int> TotalMarks5 { get; set; }
        public Nullable<int> CourseId6 { get; set; }
        public string CourseTitle6 { get; set; }
        public Nullable<int> CreditHours6 { get; set; }
        public Nullable<int> ObtainedMarks6 { get; set; }
        public Nullable<int> TotalMarks6 { get; set; }
    
        public virtual Gpa Gpa { get; set; }
        public virtual StudentRegistry StudentRegistry { get; set; }
    }
}
